[package]
name = "sand_witch_project_gdext"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]

[dependencies.godot]
version = "0.3.5"
features = [
	"experimental-threads",
	"api-4-4",
	"register-docs",
]
